#ifndef AURISYS_SCENARIO_H
#define AURISYS_SCENARIO_H

#include <stdint.h>

enum {
    /* playback */
    AURISYS_SCENARIO_PLAYBACK_NORMAL,
    AURISYS_SCENARIO_PLAYBACK_LOW_LATENCY,

    /* record */
    AURISYS_SCENARIO_RECORD_LOW_LATENCY,
    AURISYS_SCENARIO_RECORD_WITHOUT_AEC,
    AURISYS_SCENARIO_RECORD_WITH_AEC,
    AURISYS_SCENARIO_RECORD_IEM,

    /* voip */
    AURISYS_SCENARIO_VOIP,
    AURISYS_SCENARIO_VOIP_WITHOUT_AEC,

    /* call */
    AURISYS_SCENARIO_PHONE_CALL,

    /* smart pa */
    AURISYS_SCENARIO_PLAYBACK_SMARTPA,

    /* hdr record */
    AURISYS_SCENARIO_HDR_RECORD,

    /* control */
    AURISYS_SCENARIO_SIZE,
    AURISYS_SCENARIO_ALL,

    AURISYS_SCENARIO_INVALID = 0xFFFFFFFF
};



#endif /* end of AURISYS_SCENARIO_H */

